//
//  ClipboardService.swift
//  boringNotch
//

import AppKit
import Foundation

// MARK: - Pasteboard monitor

@MainActor
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    var onNewContent: ((ClipboardContent) -> Void)?

    private static let maxImageBytes = 5_000_000

    // Standard clipboard-manager etiquette: never record transient or
    // concealed (password manager) pasteboard contents.
    private static let skippedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let t = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call after the app itself writes to the pasteboard so its own
    /// copies are not re-ingested as new history items.
    func markOwnChange() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.skippedTypes.contains($0) }) else { return }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            onNewContent?(.text(string))
        } else if let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png),
                  let rep = NSBitmapImageRep(data: imageData),
                  let png = rep.representation(using: .png, properties: [:]),
                  png.count <= Self.maxImageBytes {
            onNewContent?(.image(png))
        }
    }
}

// MARK: - Persistence

final class ClipboardPersistenceService {
    static let shared = ClipboardPersistenceService()

    private let fileURL: URL
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()

    private init() {
        let fm = FileManager.default
        let support = try? fm.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        let dir = (support ?? fm.temporaryDirectory).appendingPathComponent("boringNotch", isDirectory: true).appendingPathComponent("Clipboard", isDirectory: true)
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        fileURL = dir.appendingPathComponent("history.json")
        decoder.dateDecodingStrategy = .iso8601
        encoder.dateEncodingStrategy = .iso8601
    }

    func load() -> [ClipboardItem] {
        guard let data = try? Data(contentsOf: fileURL) else { return [] }

        if let items = try? decoder.decode([ClipboardItem].self, from: data) {
            return items
        }

        // If array decoding fails, salvage individual items
        do {
            guard let jsonArray = try JSONSerialization.jsonObject(with: data) as? [Any] else {
                print("⚠️ Clipboard persistence file is not a valid JSON array")
                return []
            }

            var validItems: [ClipboardItem] = []
            var failedCount = 0

            for (index, jsonItem) in jsonArray.enumerated() {
                do {
                    let itemData = try JSONSerialization.data(withJSONObject: jsonItem)
                    let item = try decoder.decode(ClipboardItem.self, from: itemData)
                    validItems.append(item)
                } catch {
                    failedCount += 1
                    print("⚠️ Failed to decode clipboard item at index \(index): \(error.localizedDescription)")
                }
            }

            if failedCount > 0 {
                print("📋 Loaded \(validItems.count) clipboard items, discarded \(failedCount) corrupted items")
            }

            return validItems
        } catch {
            print("❌ Failed to parse clipboard persistence file: \(error.localizedDescription)")
            return []
        }
    }

    func save(_ items: [ClipboardItem]) {
        do {
            let data = try encoder.encode(items)
            try data.write(to: fileURL, options: .atomic)
        } catch {
            print("Failed to save clipboard items: \(error.localizedDescription)")
        }
    }
}
